parser: babel-eslint
env:
  browser: true
  es6: true
extends: 
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:flowtype/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - flowtype
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/prop-types: off
