language: node_js
node_js:
    - 10.15
deploy:
    - provider: pages
      github-token: $GITHUB_TOKEN
      repo: chip8-net/chip8-net.github.io
      fqdn: www.chip8.net
      local-dir: dist
      skip-cleanup: true
      on:
          branch: master